<?php

use Illuminate\Database\Seeder;

class ParishTableSeeder extends Seeder {

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $this->command->info("*** Empezando creacion de Parish! ***");
    DB::statement("INSERT INTO parishes
      (town_id, description, created_at, updated_at)
      VALUES
      (1, 'Altagracia', current_timestamp, current_timestamp),
      (1, 'Antímano', current_timestamp, current_timestamp),
      (1, 'Caricuao', current_timestamp, current_timestamp),
      (1, 'Catedral', current_timestamp, current_timestamp),
      (1, 'Coche', current_timestamp, current_timestamp),
      (1, 'El Junquito', current_timestamp, current_timestamp),
      (1, 'El paraíso', current_timestamp, current_timestamp),
      (1, 'El Recreo', current_timestamp, current_timestamp),
      (1, 'El Valle', current_timestamp, current_timestamp),
      (1, 'La Candelaria', current_timestamp, current_timestamp),
      (1, 'La Pastora', current_timestamp, current_timestamp),
      (1, 'La Vega', current_timestamp, current_timestamp),
      (1, 'Macarao', current_timestamp, current_timestamp),
      (1, 'San Agustín', current_timestamp, current_timestamp),
      (1, 'San Bernardino', current_timestamp, current_timestamp),
      (1, 'San José', current_timestamp, current_timestamp),
      (1, 'San Juan', current_timestamp, current_timestamp),
      (1, 'Santa Rosalia', current_timestamp, current_timestamp),
      (1, 'Santa Teresa', current_timestamp, current_timestamp),
      (1, 'Sucre', current_timestamp, current_timestamp),
      (1, '23 de enero', current_timestamp, current_timestamp),
      (1, 'San Pedro', current_timestamp, current_timestamp),
      (2, 'El Cafetal', current_timestamp, current_timestamp),
      (2, 'Las minas de Baruta', current_timestamp, current_timestamp),
      (2, 'Nuestra Señora del Rosario', current_timestamp, current_timestamp),
      (3, 'Chacao', current_timestamp, current_timestamp),
      (4, 'Petare', current_timestamp, current_timestamp),
      (4, 'Leoncio Martinez', current_timestamp, current_timestamp),
      (4, 'La Dolorita', current_timestamp, current_timestamp),
      (4, 'Caucaguita', current_timestamp, current_timestamp),
      (4, 'Filas de Mariche', current_timestamp, current_timestamp),
      (6, 'Araguita', current_timestamp, current_timestamp),
      (6, 'Arevalo Gonzalez', current_timestamp, current_timestamp),
      (6, 'Capaya', current_timestamp, current_timestamp),
      (6, 'Caucagua', current_timestamp, current_timestamp),
      (6, 'El Cafe', current_timestamp, current_timestamp),
      (6, 'Marizapa', current_timestamp, current_timestamp),
      (6, 'Panaquire', current_timestamp, current_timestamp),
      (6, 'Ribas', current_timestamp, current_timestamp),
      (7, 'Cumbo', current_timestamp, current_timestamp),
      (7, 'San Jose Barlovento', current_timestamp, current_timestamp),
      (8, 'Curiepe', current_timestamp, current_timestamp),
      (8, 'Higuerote', current_timestamp, current_timestamp),
      (8, 'Tacarigua', current_timestamp, current_timestamp),
      (9, 'Mamporal', current_timestamp, current_timestamp),
      (10, 'Carrizal', current_timestamp, current_timestamp),
      (11, 'Charallave', current_timestamp, current_timestamp),
      (11, 'Las Brisas', current_timestamp, current_timestamp),
      (12, 'Altagracia de la M', current_timestamp, current_timestamp),
      (12, 'Cecilio Acosta', current_timestamp, current_timestamp),
      (12, 'El Jarillo', current_timestamp, current_timestamp),
      (12, 'Los Teques', current_timestamp, current_timestamp),
      (12, 'Paracotos', current_timestamp, current_timestamp),
      (12, 'San Pedro', current_timestamp, current_timestamp),
      (12, 'Tacata', current_timestamp, current_timestamp),
      (13, 'El Cartanal', current_timestamp, current_timestamp),
      (13, 'Sta Teresa del Tuy', current_timestamp, current_timestamp),
      (14, 'La Democracia', current_timestamp, current_timestamp),
      (14, 'Ocumare del Tuy', current_timestamp, current_timestamp),
      (14, 'Santa Barbara', current_timestamp, current_timestamp),
      (15, 'San Antonio de los altos', current_timestamp, current_timestamp),
      (16, 'El Guapo', current_timestamp, current_timestamp),
      (16, 'Paparo', current_timestamp, current_timestamp),
      (16, 'Tacarigua de la laguna', current_timestamp, current_timestamp),
      (16, 'Rio Chico', current_timestamp, current_timestamp),
      (16, 'San Fernardo del Guapo', current_timestamp, current_timestamp),
      (17, 'Santa Lucia', current_timestamp, current_timestamp),
      (18, 'Cupira', current_timestamp, current_timestamp),
      (18, 'Machurucuto', current_timestamp, current_timestamp),
      (19, 'Guarenas', current_timestamp, current_timestamp),
      (20, 'San Francisco de Yare', current_timestamp, current_timestamp),
      (20, 'San Antonio de Yare', current_timestamp, current_timestamp),
      (21, 'Cua', current_timestamp, current_timestamp),
      (21, 'Nueva Cua', current_timestamp, current_timestamp),
      (22, 'Bolivar', current_timestamp, current_timestamp),
      (22, 'Guatire', current_timestamp, current_timestamp),
      (23, 'Caraballeda', current_timestamp, current_timestamp),
      (23, 'Carayaca', current_timestamp, current_timestamp),
      (23, 'Carlos Soublette', current_timestamp, current_timestamp),
      (23, 'Caruao', current_timestamp, current_timestamp),
      (23, 'Catia la mar', current_timestamp, current_timestamp),
      (23, 'El Junko', current_timestamp, current_timestamp),
      (23, 'La Guaira', current_timestamp, current_timestamp),
      (23, 'Macuto', current_timestamp, current_timestamp),
      (23, 'Maiquetia', current_timestamp, current_timestamp),
      (23, 'Naiguata', current_timestamp, current_timestamp),
      (23, 'Urimare', current_timestamp, current_timestamp),
      (24, 'Camaguan', current_timestamp, current_timestamp),
      (24, 'Puerto Miranda', current_timestamp, current_timestamp),
      (24, 'Uverito', current_timestamp, current_timestamp),
      (25, 'Chaguaramas', current_timestamp, current_timestamp),
      (26, 'El Socorro', current_timestamp, current_timestamp),
      (27, 'Calabozo', current_timestamp, current_timestamp),
      (27, 'El Calvario', current_timestamp, current_timestamp),
      (27, 'El rastro', current_timestamp, current_timestamp),
      (27, 'Guardatinajas', current_timestamp, current_timestamp),
      (28, 'San Rafael de Laya', current_timestamp, current_timestamp),
      (28, 'Tucupido', current_timestamp, current_timestamp),
      (29, 'Altagracia de Orituco', current_timestamp, current_timestamp),
      (29, 'Lezama', current_timestamp, current_timestamp),
      (29, 'Libertad de Orituco', current_timestamp, current_timestamp),
      (29, 'Paso real de Macaira', current_timestamp, current_timestamp),
      (29, 'San Fco de Macaira', current_timestamp, current_timestamp),
      (29, 'San Rafael de Orituco', current_timestamp, current_timestamp),
      (29, 'Soublette', current_timestamp, current_timestamp),
      (30, 'Cantagallo', current_timestamp, current_timestamp),
      (30, 'Parapara', current_timestamp, current_timestamp),
      (30, 'San Juan de los Morros', current_timestamp, current_timestamp),
      (31, 'El Sombrero', current_timestamp, current_timestamp),
      (31, 'Sosa', current_timestamp, current_timestamp),
      (32, 'Cabruta', current_timestamp, current_timestamp),
      (32, 'Las Mercedes', current_timestamp, current_timestamp),
      (32, 'Santa Rita de Manapire', current_timestamp, current_timestamp),
      (33, 'Espino', current_timestamp, current_timestamp),
      (33, 'Valle de la Pascua', current_timestamp, current_timestamp),
      (34, 'Ortiz', current_timestamp, current_timestamp),
      (34, 'Sn Fco de Tiznados', current_timestamp, current_timestamp),
      (34, 'San Jose de Tiznados', current_timestamp, current_timestamp),
      (34, 'Sn Lorenzo de tiznados', current_timestamp, current_timestamp),
      (35, 'San Jose de Unare', current_timestamp, current_timestamp),
      (35, 'Zaraza', current_timestamp, current_timestamp),
      (36, 'Cazorla', current_timestamp, current_timestamp),
      (36, 'Guayabal', current_timestamp, current_timestamp),
      (37, 'San Jose de Guaribe', current_timestamp, current_timestamp),
      (38, 'Altamira', current_timestamp, current_timestamp),
      (38, 'Santa Maria de Ipire', current_timestamp, current_timestamp),
      (39, 'San Mateo', current_timestamp, current_timestamp),
      (41, 'Carmen de Cura', current_timestamp, current_timestamp),
      (41, 'Camatagua', current_timestamp, current_timestamp),
      (42, 'Santa Rita', current_timestamp, current_timestamp),
      (42, 'Francisco de Miranda', current_timestamp, current_timestamp),
      (42, 'Mons Feliciano', current_timestamp, current_timestamp),
      (43, 'Andres Eloy Blanco', current_timestamp, current_timestamp),
      (43, 'Choroni', current_timestamp, current_timestamp),
      (43, 'Joaquin Crespo', current_timestamp, current_timestamp),
      (43, 'Jose Casanova Godoy', current_timestamp, current_timestamp),
      (43, 'Las Delicias', current_timestamp, current_timestamp),
      (43, 'Los Tacariguas', current_timestamp, current_timestamp),
      (43, 'Madre Ma de San Jose', current_timestamp, current_timestamp),
      (43, 'Pedro Jose Ovalies', current_timestamp, current_timestamp),
      (44, 'Santa Cruz', current_timestamp, current_timestamp),
      (45, 'Castor Nieves Rios', current_timestamp, current_timestamp),
      (45, 'La Victoria', current_timestamp, current_timestamp),
      (45, 'Las Guacamayas', current_timestamp, current_timestamp),
      (45, 'Pao de Zarate', current_timestamp, current_timestamp),
      (45, 'Zuata', current_timestamp, current_timestamp),
      (46, 'El Consejo', current_timestamp, current_timestamp),
      (47, 'Palo Negro', current_timestamp, current_timestamp),
      (47, 'Martin de Porres', current_timestamp, current_timestamp),
      (48, 'Ca de Azucar', current_timestamp, current_timestamp),
      (48, 'El Limon', current_timestamp, current_timestamp),
      (49, 'Ocumare de la costa', current_timestamp, current_timestamp),
      (50, 'San Casimiro', current_timestamp, current_timestamp),
      (50, 'Guiripa', current_timestamp, current_timestamp),
      (50, 'Ollas de Caramacate', current_timestamp, current_timestamp),
      (50, 'Valle Morin', current_timestamp, current_timestamp),
      (51, 'San Sebastian', current_timestamp, current_timestamp),
      (52, 'Alfredo Pacheco', current_timestamp, current_timestamp),
      (52, 'Arevalo Aponte', current_timestamp, current_timestamp),
      (52, 'Chuao', current_timestamp, current_timestamp),
      (52, 'Turumero', current_timestamp, current_timestamp),
      (52, 'Saman de Guere', current_timestamp, current_timestamp),
      (53, 'Las Tejerias', current_timestamp, current_timestamp),
      (53, 'Tiara', current_timestamp, current_timestamp),
      (54, 'Bella Vista', current_timestamp, current_timestamp),
      (54, 'Cagua', current_timestamp, current_timestamp),
      (55, 'Colonia Tovar', current_timestamp, current_timestamp),
      (56, 'Barbacoas', current_timestamp, current_timestamp),
      (56, 'Las Peñitas', current_timestamp, current_timestamp),
      (56, 'San Francisco de Cara', current_timestamp, current_timestamp),
      (56, 'Taguay', current_timestamp, current_timestamp),
      (57, 'Augusto Mijares', current_timestamp, current_timestamp),
      (57, 'Villa de cura', current_timestamp, current_timestamp),
      (57, 'Magdaleno', current_timestamp, current_timestamp),
      (57, 'Sam Francisco de Asis', current_timestamp, current_timestamp),
      (57, 'Valles de Tucutunemo', current_timestamp, current_timestamp),
      (58, 'Bejuma', current_timestamp, current_timestamp),
      (58, 'Canoabo', current_timestamp, current_timestamp),
      (58, 'Simon Bolivar', current_timestamp, current_timestamp),
      (59, 'Belen', current_timestamp, current_timestamp),
      (59, 'Guigue', current_timestamp, current_timestamp),
      (59, 'Tacarigua', current_timestamp, current_timestamp),
      (60, 'Agua Caliente', current_timestamp, current_timestamp),
      (60, 'Mariara', current_timestamp, current_timestamp),
      (61, 'Ciudad Alianza', current_timestamp, current_timestamp),
      (61, 'Guacara', current_timestamp, current_timestamp),
      (61, 'Yagua', current_timestamp, current_timestamp),
      (62, 'Moron', current_timestamp, current_timestamp),
      (62, 'Urama', current_timestamp, current_timestamp),
      (63, 'Independencia', current_timestamp, current_timestamp),
      (63, 'Tocuyito', current_timestamp, current_timestamp),
      (64, 'Los Guayos', current_timestamp, current_timestamp),
      (65, 'Miranda', current_timestamp, current_timestamp),
      (66, 'Montalban', current_timestamp, current_timestamp),
      (67, 'Naguanagua', current_timestamp, current_timestamp),
      (68, 'Bartolome Salom', current_timestamp, current_timestamp),
      (68, 'Borburata', current_timestamp, current_timestamp),
      (68, 'Democracia', current_timestamp, current_timestamp),
      (68, 'Fraternidad', current_timestamp, current_timestamp),
      (68, 'Goaigoaza', current_timestamp, current_timestamp),
      (68, 'Juan Jose Flores', current_timestamp, current_timestamp),
      (68, 'Patanemo', current_timestamp, current_timestamp),
      (68, 'Union', current_timestamp, current_timestamp),
      (69, 'San Diego', current_timestamp, current_timestamp),
      (70, 'San Joaquin', current_timestamp, current_timestamp),
      (71, 'Candelaria', current_timestamp, current_timestamp),
      (71, 'Catedral', current_timestamp, current_timestamp),
      (71, 'El Socorro', current_timestamp, current_timestamp),
      (71, 'Miguel Peña', current_timestamp, current_timestamp),
      (71, 'Negro Primero', current_timestamp, current_timestamp),
      (71, 'Rafael Urdaneta', current_timestamp, current_timestamp),
      (71, 'San Bias', current_timestamp, current_timestamp),
      (71, 'San Jose', current_timestamp, current_timestamp),
      (71, 'Santa Rosa', current_timestamp, current_timestamp),
      (5, 'El Hatillo', current_timestamp, current_timestamp),
      (93, 'Alto Orinoco La Esmeralda', current_timestamp, current_timestamp),
      (93, 'Huachamacare Acanaña', current_timestamp, current_timestamp),
      (93, 'Marawaka Toky Shamanaña', current_timestamp, current_timestamp),
      (93, 'Mavaka Mavaka', current_timestamp, current_timestamp),
      (93, 'Sierra Parima Parimabé', current_timestamp, current_timestamp),
      (94, 'Ucata Laja Lisa', current_timestamp, current_timestamp),
      (94, 'Yapacana Macuruco', current_timestamp, current_timestamp),
      (94, 'Caname Guarinuma', current_timestamp, current_timestamp),
      (95, 'Fernando Girón Tovar Puerto Ayacucho', current_timestamp, current_timestamp),
      (95, 'Luis Alberto Gómez Puerto Ayacucho', current_timestamp, current_timestamp),
      (95, 'Pahueña Limón de Parhueña', current_timestamp, current_timestamp),
      (95, 'Platanillal Platanillal', current_timestamp, current_timestamp),
      (96, 'Samariapo Samariapo', current_timestamp, current_timestamp),
      (96, 'Sipapo Pendare', current_timestamp, current_timestamp),
      (96, 'Munduapo Munduapo', current_timestamp, current_timestamp),
      (96, 'Guayapo San Pedro del Orinoco', current_timestamp, current_timestamp),
      (97, 'Alto Ventuari Cacurí', current_timestamp, current_timestamp),
      (97, 'Medio Ventuari Manami', current_timestamp, current_timestamp),
      (97, 'Ventuari Marueta', current_timestamp, current_timestamp),
      (98, 'Victorino', current_timestamp, current_timestamp),
      (98, 'Comunidad', current_timestamp, current_timestamp),
      (99, 'Casiquiare Curimacare', current_timestamp, current_timestamp),
      (99, 'Cucuy', current_timestamp, current_timestamp),
      (99, 'Casiquiare Curimacare', current_timestamp, current_timestamp),
      (99, 'Solano Solano', current_timestamp, current_timestamp),
      (72, 'Anaco', current_timestamp, current_timestamp),
      (72, 'San Joaquín', current_timestamp, current_timestamp),
      (73, 'Cachipo', current_timestamp, current_timestamp),
      (73, 'Aragua de Barcelona', current_timestamp, current_timestamp),
      (78, 'Lechería', current_timestamp, current_timestamp),
      (78, 'El Morro', current_timestamp, current_timestamp),
      (87, 'Puerto Píritu', current_timestamp, current_timestamp),
      (87, 'San Miguel', current_timestamp, current_timestamp),
      (87, 'Sucre', current_timestamp, current_timestamp),
      (77, 'Valle de Guanape', current_timestamp, current_timestamp),
      (77, 'Santa Bárbara', current_timestamp, current_timestamp),
      (85, 'Atapirire', current_timestamp, current_timestamp),
      (85, 'Boca del Pao', current_timestamp, current_timestamp),
      (85, 'El Pao', current_timestamp, current_timestamp),
      (85, 'Pariaguán', current_timestamp, current_timestamp),
      (81, 'Guanta', current_timestamp, current_timestamp),
      (81, 'Chorrerón', current_timestamp, current_timestamp),
      (82, 'Mamo', current_timestamp, current_timestamp),
      (82, 'Soledad', current_timestamp, current_timestamp),
      (86, 'Mapire', current_timestamp, current_timestamp),
      (86, 'Piar', current_timestamp, current_timestamp),
      (86, 'Santa Clara', current_timestamp, current_timestamp),
      (86, 'San Diego de Cabrutica', current_timestamp, current_timestamp),
      (86, 'Uverito', current_timestamp, current_timestamp),
      (86, 'Zuata', current_timestamp, current_timestamp),
      (92, 'Puerto La Cruz', current_timestamp, current_timestamp),
      (92, 'Pozuelos', current_timestamp, current_timestamp),
      (76, 'Onoto', current_timestamp, current_timestamp),
      (76, 'San Pablo', current_timestamp, current_timestamp),
      (83, 'San Mateo', current_timestamp, current_timestamp),
      (83, 'El Carito', current_timestamp, current_timestamp),
      (83, 'Santa Inés', current_timestamp, current_timestamp),
      (83, 'La Romereña', current_timestamp, current_timestamp),
      (75, 'Clarines', current_timestamp, current_timestamp),
      (75, 'Guanape', current_timestamp, current_timestamp),
      (75, 'Sabana de Uchire', current_timestamp, current_timestamp),
      (79, 'Cantaura', current_timestamp, current_timestamp),
      (79, 'Libertador', current_timestamp, current_timestamp),
      (79, 'Santa Rosa', current_timestamp, current_timestamp),
      (79, 'Urica', current_timestamp, current_timestamp),
      (88, 'Píritu', current_timestamp, current_timestamp),
      (88, 'San Francisco', current_timestamp, current_timestamp),
      (80, 'San José de Guanipa', current_timestamp, current_timestamp),
      (89, 'Boca de Uchire', current_timestamp, current_timestamp),
      (89, 'Boca de Chávez', current_timestamp, current_timestamp),
      (90, 'Pueblo Nuevo', current_timestamp, current_timestamp),
      (90, 'Santa Ana', current_timestamp, current_timestamp),
      (74, 'Bergatín', current_timestamp, current_timestamp),
      (74, 'Caigua', current_timestamp, current_timestamp),
      (74, 'El Carmen', current_timestamp, current_timestamp),
      (74, 'El Pilar', current_timestamp, current_timestamp),
      (74, 'Naricual', current_timestamp, current_timestamp),
      (74, 'San Cristóbal', current_timestamp, current_timestamp),
      (91, 'Edmundo Barrios', current_timestamp, current_timestamp),
      (91, 'Miguel Otero Silva', current_timestamp, current_timestamp),
      (84, 'El Chaparro', current_timestamp, current_timestamp),
      (84, 'Tomás Alfaro', current_timestamp, current_timestamp),
      (84, 'Calatrava', current_timestamp, current_timestamp),
      (100, 'Achaguas', current_timestamp, current_timestamp);");
    DB::statement("INSERT INTO parishes
      (town_id, description, created_at, updated_at)
      VALUES
      (100, 'Apurito', current_timestamp, current_timestamp),
      (100, 'El Yagual', current_timestamp, current_timestamp),
      (100, 'Guachara', current_timestamp, current_timestamp),
      (100, 'Mucuritas', current_timestamp, current_timestamp),
      (100, 'Queseras del medio', current_timestamp, current_timestamp),
      (101, 'Biruaca', current_timestamp, current_timestamp),
      (102, 'Bruzual', current_timestamp, current_timestamp),
      (102, 'Mantecal', current_timestamp, current_timestamp),
      (102, 'Quintero', current_timestamp, current_timestamp),
      (102, 'Rincón Hondo', current_timestamp, current_timestamp),
      (102, 'San Vicente', current_timestamp, current_timestamp),
      (104, 'San Juan de Payara', current_timestamp, current_timestamp),
      (104, 'Codazzzi', current_timestamp, current_timestamp),
      (104, 'Cunaviche', current_timestamp, current_timestamp),
      (106, 'San Fernando', current_timestamp, current_timestamp),
      (106, 'El Recre0', current_timestamp, current_timestamp),
      (106, 'Peñalver', current_timestamp, current_timestamp),
      (106, 'San Rafael de Atamaica', current_timestamp, current_timestamp),
      (103, 'Guasdualito', current_timestamp, current_timestamp),
      (103, 'Aramendi', current_timestamp, current_timestamp),
      (103, 'El Amparo', current_timestamp, current_timestamp),
      (103, 'San Camilo', current_timestamp, current_timestamp),
      (103, 'Urdaneta', current_timestamp, current_timestamp),
      (105, 'Elorza', current_timestamp, current_timestamp),
      (105, 'La Trinidad', current_timestamp, current_timestamp),
      (107, 'Sabaneta', current_timestamp, current_timestamp),
      (107, 'Juan Antonio Rodríguez Domínguez', current_timestamp, current_timestamp),
      (108, 'El Cantón', current_timestamp, current_timestamp),
      (108, 'Santa Cruz de Guacas', current_timestamp, current_timestamp),
      (108, 'Puerto Vivas', current_timestamp, current_timestamp),
      (109, 'Ticoporo', current_timestamp, current_timestamp),
      (109, 'Nicolás Pulido', current_timestamp, current_timestamp),
      (109, 'Andrés Bello', current_timestamp, current_timestamp),
      (110, 'Arismendi', current_timestamp, current_timestamp),
      (110, 'Guadarrama', current_timestamp, current_timestamp),
      (110, 'La Unión', current_timestamp, current_timestamp),
      (110, 'San Antonio', current_timestamp, current_timestamp),
      (111, 'Barinas', current_timestamp, current_timestamp),
      (111, 'Alberto Arvelo Larriva', current_timestamp, current_timestamp),
      (111, 'San Silvestre', current_timestamp, current_timestamp),
      (111, 'Santa Inés', current_timestamp, current_timestamp),
      (111, 'Santa Lucía', current_timestamp, current_timestamp),
      (111, 'Torunos', current_timestamp, current_timestamp),
      (111, 'El Carmen', current_timestamp, current_timestamp),
      (111, 'Rómulo Betancourt', current_timestamp, current_timestamp),
      (111, 'Corazón de Jesús', current_timestamp, current_timestamp),
      (111, 'Ramón Ignacio', current_timestamp, current_timestamp),
      (111, 'Alto Barinas', current_timestamp, current_timestamp),
      (111, 'Manuel Palacio Fajardo', current_timestamp, current_timestamp),
      (111, 'Juan Antonio Rodríguez Domínguez', current_timestamp, current_timestamp),
      (111, 'Dominga Ortiz de Páez', current_timestamp, current_timestamp),
      (112, 'Barinitas', current_timestamp, current_timestamp),
      (112, 'Altamira de Cáceres', current_timestamp, current_timestamp),
      (112, 'Calderas', current_timestamp, current_timestamp),
      (113, 'Barracas', current_timestamp, current_timestamp),
      (113, 'El Socorro', current_timestamp, current_timestamp),
      (113, 'Mazparrito', current_timestamp, current_timestamp),
      (114, 'Santa Bárbara', current_timestamp, current_timestamp),
      (114, 'Pedro Briceño Méndez', current_timestamp, current_timestamp),
      (114, 'Ramón Ignacio Méndez', current_timestamp, current_timestamp),
      (114, 'José Ignacio del Pumar', current_timestamp, current_timestamp),
      (115, 'Obispos', current_timestamp, current_timestamp),
      (115, 'Los Guasimitos', current_timestamp, current_timestamp),
      (115, 'El Real', current_timestamp, current_timestamp),
      (115, 'La Luz', current_timestamp, current_timestamp),
      (116, 'Ciudad Bolívia', current_timestamp, current_timestamp),
      (116, 'José Ignacio Briceño', current_timestamp, current_timestamp),
      (116, 'José Félix Ribas', current_timestamp, current_timestamp),
      (116, 'Páez', current_timestamp, current_timestamp),
      (117, 'Libertad', current_timestamp, current_timestamp),
      (117, 'Dolores', current_timestamp, current_timestamp),
      (117, 'Santa Rosa', current_timestamp, current_timestamp),
      (117, 'Palacio Fajardo', current_timestamp, current_timestamp),
      (117, 'Simón Rodríguez', current_timestamp, current_timestamp),
      (118, 'Ciudad de Nutrias', current_timestamp, current_timestamp),
      (118, 'El Regalo', current_timestamp, current_timestamp),
      (118, 'Puerto Nutrias', current_timestamp, current_timestamp),
      (118, 'Santa Catalina', current_timestamp, current_timestamp),
      (118, 'Simón Bolívar', current_timestamp, current_timestamp),
      (119, 'Cachamay', current_timestamp, current_timestamp),
      (119, 'Chirica', current_timestamp, current_timestamp),
      (119, 'Dalla Costa', current_timestamp, current_timestamp),
      (119, 'Once de Abril', current_timestamp, current_timestamp),
      (119, 'Simón Bolívar', current_timestamp, current_timestamp),
      (119, 'Unare', current_timestamp, current_timestamp),
      (119, 'Universidad', current_timestamp, current_timestamp),
      (119, 'Vista al Sol', current_timestamp, current_timestamp),
      (119, 'Pozo Verde', current_timestamp, current_timestamp),
      (119, 'Yocoima', current_timestamp, current_timestamp),
      (119, '5 de Julio', current_timestamp, current_timestamp),
      (120, 'Cedeño', current_timestamp, current_timestamp),
      (120, 'Altagracia', current_timestamp, current_timestamp),
      (120, 'Ascensión Farreras', current_timestamp, current_timestamp),
      (120, 'Guaniamo', current_timestamp, current_timestamp),
      (120, 'La Urbana', current_timestamp, current_timestamp),
      (120, 'Pijiguaos', current_timestamp, current_timestamp),
      (121, 'El Callao', current_timestamp, current_timestamp),
      (122, 'Gran Sabana', current_timestamp, current_timestamp),
      (122, 'Ikabarú', current_timestamp, current_timestamp),
      (123, 'Catedral', current_timestamp, current_timestamp),
      (123, 'Zea', current_timestamp, current_timestamp),
      (123, 'Orinoco', current_timestamp, current_timestamp),
      (123, 'José Antonio Páez', current_timestamp, current_timestamp),
      (123, 'Marhuanta', current_timestamp, current_timestamp),
      (123, 'Agua Salada', current_timestamp, current_timestamp),
      (123, 'Vista Hermosa', current_timestamp, current_timestamp),
      (123, 'La Sabanita', current_timestamp, current_timestamp),
      (123, 'Panapana', current_timestamp, current_timestamp),
      (129, 'Padre Pedro Chien', current_timestamp, current_timestamp),
      (129, 'Río Grande', current_timestamp, current_timestamp),
      (124, 'Andrés Eloy Blanco', current_timestamp, current_timestamp),
      (124, 'Pedro Cova', current_timestamp, current_timestamp),
      (125, 'Raúl Leoni', current_timestamp, current_timestamp),
      (125, 'Barceloneta', current_timestamp, current_timestamp),
      (125, 'Santa Bárbara', current_timestamp, current_timestamp),
      (125, 'San Francisco', current_timestamp, current_timestamp),
      (126, 'Roscio', current_timestamp, current_timestamp),
      (126, 'Salóm', current_timestamp, current_timestamp),
      (127, 'Sifontes', current_timestamp, current_timestamp),
      (127, 'Dalla Costa', current_timestamp, current_timestamp),
      (127, 'San Isidro ', current_timestamp, current_timestamp),
      (128, 'Sucre', current_timestamp, current_timestamp),
      (128, 'Aripao', current_timestamp, current_timestamp),
      (128, 'Guarataro', current_timestamp, current_timestamp),
      (128, 'Las Majadas', current_timestamp, current_timestamp),
      (128, 'Moitaco ', current_timestamp, current_timestamp),
      (130, 'Cojedes', current_timestamp, current_timestamp),
      (130, 'Juan de Mata Suárez', current_timestamp, current_timestamp),
      (134, 'El Pao', current_timestamp, current_timestamp),
      (131, 'Tinaquillo', current_timestamp, current_timestamp),
      (132, 'El Baúl', current_timestamp, current_timestamp),
      (132, 'Sucre', current_timestamp, current_timestamp),
      (133, 'La Aguadita', current_timestamp, current_timestamp),
      (133, 'Macapo', current_timestamp, current_timestamp),
      (135, 'El Amparo', current_timestamp, current_timestamp),
      (135, 'Libertad de Cojedes', current_timestamp, current_timestamp),
      (136, 'Rómulo Gallegos', current_timestamp, current_timestamp),
      (137, 'San Carlos de Austria', current_timestamp, current_timestamp),
      (137, 'Juan Ángel Bravo', current_timestamp, current_timestamp),
      (137, 'Manuel Manrique', current_timestamp, current_timestamp),
      (138, 'General en Jefe José Laurencio Silva', current_timestamp, current_timestamp),
      (139, 'Curiapo', current_timestamp, current_timestamp),
      (139, 'Almirante Luis Brión', current_timestamp, current_timestamp),
      (139, 'Francisco Aniceto Lugo Boca de Cuyubini', current_timestamp, current_timestamp),
      (139, 'Manuel Renaud', current_timestamp, current_timestamp),
      (139, 'Padre Barral', current_timestamp, current_timestamp),
      (139, 'Santos de Abelgas', current_timestamp, current_timestamp),
      (140, 'Imataca Moruca', current_timestamp, current_timestamp),
      (140, 'Cinco de Julio Piacoa', current_timestamp, current_timestamp),
      (140, 'Juan Bautista Arismendi', current_timestamp, current_timestamp),
      (140, 'Manuel Piar Santa Catalina', current_timestamp, current_timestamp),
      (140, 'Rómulo Gallegos', current_timestamp, current_timestamp),
      (141, 'Pedernales', current_timestamp, current_timestamp),
      (141, 'Luis Beltrán Prieto Figueroa', current_timestamp, current_timestamp),
      (142, 'San José (Delta Amacuro) Hacienda del Medio', current_timestamp, current_timestamp),
      (142, 'José Vidal Marcano Caparal de Guara', current_timestamp, current_timestamp),
      (142, 'Juan Millán Urbanización Leonardo Ruíz Pineda', current_timestamp, current_timestamp),
      (142, 'Leonardo Ruíz Pineda Paloma', current_timestamp, current_timestamp),
      (142, 'Mariscal Antonio José de Sucre Urbanización Delfín Mendoza', current_timestamp, current_timestamp),
      (142, 'Monseñor Argimiro García San Rafael', current_timestamp, current_timestamp),
      (142, 'San Rafael', current_timestamp, current_timestamp),
      (142, 'Virgen del Valle', current_timestamp, current_timestamp),
      (143, 'Capadare', current_timestamp, current_timestamp),
      (143, 'La Pastora', current_timestamp, current_timestamp),
      (143, 'Libertador', current_timestamp, current_timestamp),
      (143, 'San Juan de los Cayos', current_timestamp, current_timestamp),
      (144, 'Aracua', current_timestamp, current_timestamp),
      (144, 'La Peña', current_timestamp, current_timestamp),
      (144, 'San Luis', current_timestamp, current_timestamp),
      (145, 'Bariro', current_timestamp, current_timestamp),
      (145, 'Borojó', current_timestamp, current_timestamp),
      (145, 'Capatárida', current_timestamp, current_timestamp),
      (145, 'Guajiro', current_timestamp, current_timestamp),
      (145, 'Seque', current_timestamp, current_timestamp),
      (145, 'Zazárida', current_timestamp, current_timestamp),
      (145, 'Valle de Eroa', current_timestamp, current_timestamp),
      (146, 'Cacique Manaure', current_timestamp, current_timestamp),
      (147, 'Norte', current_timestamp, current_timestamp),
      (147, 'Carirubana', current_timestamp, current_timestamp),
      (147, 'Santa Ana', current_timestamp, current_timestamp),
      (147, 'Urbana Punta Cardón', current_timestamp, current_timestamp),
      (148, 'La Vela de Coro', current_timestamp, current_timestamp),
      (148, 'Acurigua', current_timestamp, current_timestamp),
      (148, 'Guaibacoa', current_timestamp, current_timestamp),
      (148, 'Las Calderas', current_timestamp, current_timestamp),
      (148, 'Macoruca', current_timestamp, current_timestamp),
      (149, 'Dabajuro', current_timestamp, current_timestamp),
      (150, 'Agua Clara', current_timestamp, current_timestamp),
      (150, 'Avaria', current_timestamp, current_timestamp),
      (150, 'Pedregal', current_timestamp, current_timestamp),
      (150, 'Piedra Grande', current_timestamp, current_timestamp),
      (150, 'Purureche', current_timestamp, current_timestamp),
      (151, 'Adaure', current_timestamp, current_timestamp),
      (151, 'Adícora', current_timestamp, current_timestamp),
      (151, 'Baraived', current_timestamp, current_timestamp),
      (151, 'Buena Vista', current_timestamp, current_timestamp),
      (151, 'Jadacaquiva', current_timestamp, current_timestamp),
      (151, 'El Vínculo', current_timestamp, current_timestamp),
      (151, 'El Hato', current_timestamp, current_timestamp),
      (151, 'Moruy', current_timestamp, current_timestamp),
      (151, 'Pueblo Nuevo', current_timestamp, current_timestamp);");
    DB::statement("INSERT INTO parishes
      (town_id, description, created_at, updated_at)
      VALUES
      (152, 'Agua Larga', current_timestamp, current_timestamp),
      (152, 'Churuguara', current_timestamp, current_timestamp),
      (152, 'El Paují', current_timestamp, current_timestamp),
      (152, 'Independencia', current_timestamp, current_timestamp),
      (152, 'Mapararí', current_timestamp, current_timestamp),
      (153, 'Jacura', current_timestamp, current_timestamp),
      (154, 'Los Taques', current_timestamp, current_timestamp),
      (155, 'Mene de Mauroa', current_timestamp, current_timestamp),
      (156, 'Guzmán Guillermo', current_timestamp, current_timestamp),
      (156, 'Mitare ', current_timestamp, current_timestamp),
      (156, 'Río Seco', current_timestamp, current_timestamp),
      (156, 'Sabaneta', current_timestamp, current_timestamp),
      (156, 'Santa Ana', current_timestamp, current_timestamp),
      (157, 'Boca del Tocuyo', current_timestamp, current_timestamp),
      (157, 'Chichiriviche', current_timestamp, current_timestamp),
      (158, 'Palmasola', current_timestamp, current_timestamp),
      (159, 'Cabure', current_timestamp, current_timestamp),
      (159, 'Curimagua', current_timestamp, current_timestamp),
      (160, 'San José de la Costa', current_timestamp, current_timestamp),
      (160, 'Píritu', current_timestamp, current_timestamp),
      (161, 'Capital San Francisco', current_timestamp, current_timestamp),
      (162, 'Tucacas', current_timestamp, current_timestamp),
      (162, 'Boca de Aroa', current_timestamp, current_timestamp),
      (163, 'Sucre', current_timestamp, current_timestamp),
      (164, 'Tocópero', current_timestamp, current_timestamp),
      (165, 'Santa Cruz de Bucaral', current_timestamp, current_timestamp),
      (166, 'Bruzual', current_timestamp, current_timestamp),
      (166, 'Urumaco', current_timestamp, current_timestamp),
      (167, 'Puerto Cumarebo', current_timestamp, current_timestamp),
      (167, 'La Ciénaga', current_timestamp, current_timestamp),
      (167, 'La Soledad', current_timestamp, current_timestamp),
      (167, 'Pueblo Cumarebo', current_timestamp, current_timestamp),
      (167, 'Zazárida', current_timestamp, current_timestamp),
      (168, 'Pio Tamayo', current_timestamp, current_timestamp),
      (168, 'Quebrada Honda de Guache', current_timestamp, current_timestamp),
      (169, 'Freitez', current_timestamp, current_timestamp),
      (169, 'José María Blanco', current_timestamp, current_timestamp),
      (172, 'Anzoátegui', current_timestamp, current_timestamp),
      (172, 'Bolívar', current_timestamp, current_timestamp),
      (172, 'Guárico', current_timestamp, current_timestamp),
      (172, 'Hilario Luna y Luna', current_timestamp, current_timestamp),
      (173, 'Cabudare', current_timestamp, current_timestamp),
      (173, 'Agua Viva', current_timestamp, current_timestamp),
      (172, 'Morán', current_timestamp, current_timestamp),
      (174, 'Buría', current_timestamp, current_timestamp),
      (174, 'Sarare', current_timestamp, current_timestamp),
      (175, 'Altagracia', current_timestamp, current_timestamp),
      (175, 'Lara', current_timestamp, current_timestamp),
      (175, 'Chiquinquira', current_timestamp, current_timestamp),
      (176, 'Siquisique', current_timestamp, current_timestamp),
      (176, 'Moroturo', current_timestamp, current_timestamp),
      (170, 'Barquisimeto', current_timestamp, current_timestamp),
      (171, 'Quibor', current_timestamp, current_timestamp),
      (177, 'Betancourt', current_timestamp, current_timestamp),
      (177, 'Páez', current_timestamp, current_timestamp),
      (177, 'Rómulo Gallegos', current_timestamp, current_timestamp),
      (177, 'Gabriel Picón Gonzále', current_timestamp, current_timestamp),
      (177, 'Héctor Amable Mora', current_timestamp, current_timestamp),
      (178, 'La Azulita', current_timestamp, current_timestamp),
      (179, 'Santa Cruz de Mora', current_timestamp, current_timestamp),
      (179, 'Mesa de Las Palmas', current_timestamp, current_timestamp),
      (180, 'Aricagua', current_timestamp, current_timestamp),
      (181, 'Capurí', current_timestamp, current_timestamp),
      (181, 'Chacantá', current_timestamp, current_timestamp),
      (181, 'Guaimaral', current_timestamp, current_timestamp),
      (181, 'Mucuchachí', current_timestamp, current_timestamp),
      (182, 'Fernández Peña (Ejido)', current_timestamp, current_timestamp),
      (182, 'Acequias', current_timestamp, current_timestamp),
      (182, 'Jají', current_timestamp, current_timestamp),
      (182, 'La Mesa', current_timestamp, current_timestamp),
      (182, 'San José del Sur', current_timestamp, current_timestamp),
      (183, 'Tucaní', current_timestamp, current_timestamp),
      (184, 'Santo Domingo', current_timestamp, current_timestamp),
      (185, 'Guaraque', current_timestamp, current_timestamp),
      (186, 'Arapuey', current_timestamp, current_timestamp),
      (186, 'Palmira', current_timestamp, current_timestamp),
      (187, 'Torondoy', current_timestamp, current_timestamp),
      (188, 'Antonio Spinetti Dini', current_timestamp, current_timestamp),
      (188, 'Arias', current_timestamp, current_timestamp),
      (188, 'Caracciolo Parra Pérez', current_timestamp, current_timestamp),
      (188, 'Domingo Peña ', current_timestamp, current_timestamp),
      (188, 'El Llano', current_timestamp, current_timestamp),
      (188, 'Gonzalo Picón Febres', current_timestamp, current_timestamp),
      (188, 'Jacinto Plaza', current_timestamp, current_timestamp),
      (188, 'Juan Rodríguez Suárez', current_timestamp, current_timestamp),
      (188, 'Lasso de la Vega', current_timestamp, current_timestamp),
      (188, 'Mariano Picón Sala', current_timestamp, current_timestamp),
      (188, 'Milla', current_timestamp, current_timestamp),
      (188, 'Osuna Rodríguez', current_timestamp, current_timestamp),
      (188, 'Sagrario', current_timestamp, current_timestamp),
      (188, 'El Morro', current_timestamp, current_timestamp),
      (188, 'Los Nevados', current_timestamp, current_timestamp),
      (189, 'Andrés Eloy Blanco', current_timestamp, current_timestamp),
      (189, 'La Venta', current_timestamp, current_timestamp),
      (189, 'Piñango', current_timestamp, current_timestamp),
      (189, 'Timotes', current_timestamp, current_timestamp),
      (190, 'Eloy Paredes', current_timestamp, current_timestamp),
      (190, 'San Rafael de Alcázar', current_timestamp, current_timestamp),
      (191, 'Santa María de Caparo', current_timestamp, current_timestamp),
      (192, 'Pueblo Llano', current_timestamp, current_timestamp),
      (193, 'Cacute', current_timestamp, current_timestamp),
      (193, 'Mucuchíes', current_timestamp, current_timestamp),
      (194, 'Gerónimo Maldonado', current_timestamp, current_timestamp),
      (194, 'Bailadores', current_timestamp, current_timestamp),
      (195, 'Tabay', current_timestamp, current_timestamp),
      (196, 'Chiguará', current_timestamp, current_timestamp),
      (196, 'Estánquez', current_timestamp, current_timestamp),
      (196, 'Lagunillas', current_timestamp, current_timestamp),
      (196, 'Pueblo Nuevo del Sur', current_timestamp, current_timestamp),
      (196, 'San Juan', current_timestamp, current_timestamp),
      (197, 'El Amparo', current_timestamp, current_timestamp),
      (197, 'El Llano', current_timestamp, current_timestamp),
      (197, 'San Francisco', current_timestamp, current_timestamp),
      (197, 'Tovar', current_timestamp, current_timestamp),
      (198, 'Independencia', current_timestamp, current_timestamp),
      (198, 'María de la Concepción Palacios Blanco', current_timestamp, current_timestamp),
      (198, 'Nueva Bolivia', current_timestamp, current_timestamp),
      (198, 'Santa Apolonia', current_timestamp, current_timestamp),
      (199, 'Caño El Tigre', current_timestamp, current_timestamp),
      (199, 'Zea', current_timestamp, current_timestamp),
      (200, 'San Antonio de Maturín', current_timestamp, current_timestamp),
      (200, 'San Francisco de Maturín', current_timestamp, current_timestamp),
      (201, 'Aguasay', current_timestamp, current_timestamp),
      (202, 'Caripito', current_timestamp, current_timestamp),
      (203, 'El Guácharo', current_timestamp, current_timestamp),
      (203, 'Caripe', current_timestamp, current_timestamp),
      (204, 'Capital Cedeño', current_timestamp, current_timestamp),
      (204, 'San Félix de Cantalicio', current_timestamp, current_timestamp),
      (205, 'El Tejero', current_timestamp, current_timestamp),
      (205, 'Punta de Mata', current_timestamp, current_timestamp),
      (206, 'Chaguaramas', current_timestamp, current_timestamp),
      (206, 'Temblador', current_timestamp, current_timestamp),
      (207, 'Alto de los Godos', current_timestamp, current_timestamp),
      (207, 'Boquerón', current_timestamp, current_timestamp),
      (207, 'Las Cocuizas', current_timestamp, current_timestamp),
      (207, 'La Cruz', current_timestamp, current_timestamp),
      (207, 'San Simón', current_timestamp, current_timestamp),
      (207, 'El Corozo', current_timestamp, current_timestamp),
      (207, 'El Furrial', current_timestamp, current_timestamp),
      (207, 'Jusepín', current_timestamp, current_timestamp),
      (207, 'La Pica', current_timestamp, current_timestamp),
      (207, 'San Vicente', current_timestamp, current_timestamp),
      (208, 'Aparicio', current_timestamp, current_timestamp),
      (208, 'Chaguamal', current_timestamp, current_timestamp),
      (208, 'El Pinto', current_timestamp, current_timestamp),
      (208, 'Guanaguana', current_timestamp, current_timestamp),
      (208, 'La Toscana', current_timestamp, current_timestamp),
      (209, 'Cachipo', current_timestamp, current_timestamp),
      (209, 'Quiriquire', current_timestamp, current_timestamp),
      (210, 'Santa Bárbara', current_timestamp, current_timestamp),
      (211, 'Barrancas', current_timestamp, current_timestamp),
      (212, 'Uracoa', current_timestamp, current_timestamp),
      (213, 'Antolín del Campo', current_timestamp, current_timestamp),
      (214, 'Arismendi', current_timestamp, current_timestamp),
      (215, 'San Juan Bautista', current_timestamp, current_timestamp),
      (215, 'Zabala', current_timestamp, current_timestamp),
      (216, 'García', current_timestamp, current_timestamp),
      (216, 'Francisco Fajardo', current_timestamp, current_timestamp),
      (217, 'Bolívar', current_timestamp, current_timestamp),
      (217, 'Guevara', current_timestamp, current_timestamp),
      (217, 'Cerro de Matasiete', current_timestamp, current_timestamp),
      (217, 'Santa Ana', current_timestamp, current_timestamp),
      (217, 'Sucre', current_timestamp, current_timestamp),
      (218, 'Aguirre', current_timestamp, current_timestamp),
      (218, 'Maneiro', current_timestamp, current_timestamp),
      (219, 'Adrián', current_timestamp, current_timestamp),
      (219, 'Juan Griego', current_timestamp, current_timestamp),
      (219, 'Yaguaraparo', current_timestamp, current_timestamp),
      (220, 'Porlamar', current_timestamp, current_timestamp),
      (221, 'San Francisco de Macanao', current_timestamp, current_timestamp),
      (221, 'Boca de Río', current_timestamp, current_timestamp),
      (222, 'Tubores', current_timestamp, current_timestamp),
      (223, 'Villalba', current_timestamp, current_timestamp),
      (224, 'Agua Blanca', current_timestamp, current_timestamp),
      (225, 'Araure', current_timestamp, current_timestamp),
      (226, 'Píritu', current_timestamp, current_timestamp),
      (226, 'Uveral', current_timestamp, current_timestamp),
      (227, 'Guanare', current_timestamp, current_timestamp),
      (228, 'Guanarito', current_timestamp, current_timestamp),
      (229, 'Peña Blanca', current_timestamp, current_timestamp),
      (230, 'Aparición', current_timestamp, current_timestamp),
      (230, 'Ospino', current_timestamp, current_timestamp),
      (231, 'Acarigua', current_timestamp, current_timestamp),
      (231, 'Payara', current_timestamp, current_timestamp),
      (232, 'Papelón', current_timestamp, current_timestamp),
      (233, 'Boconoíto', current_timestamp, current_timestamp),
      (234, 'San Rafael de Onoto', current_timestamp, current_timestamp),
      (234, 'Santa Fé', current_timestamp, current_timestamp),
      (235, 'Florida', current_timestamp, current_timestamp),
      (235, 'El Playón', current_timestamp, current_timestamp),
      (236, 'Biscucuy', current_timestamp, current_timestamp),
      (236, 'Concepción', current_timestamp, current_timestamp),
      (236, 'San José de Saguaz', current_timestamp, current_timestamp),
      (236, 'San Rafael de Palo Alzado', current_timestamp, current_timestamp),
      (236, 'Uvencio Antonio Velásquez', current_timestamp, current_timestamp),
      (236, 'Villa Rosa', current_timestamp, current_timestamp),
      (237, 'Canelones', current_timestamp, current_timestamp),
      (237, 'Santa Cruz', current_timestamp, current_timestamp),
      (237, 'San Isidro Labrador', current_timestamp, current_timestamp),
      (238, 'Mariño', current_timestamp, current_timestamp);");
    DB::statement("INSERT INTO parishes
      (town_id, description, created_at, updated_at)
      VALUES
      (238, 'Rómulo Gallegos', current_timestamp, current_timestamp),
      (239, 'San José de Aerocuar', current_timestamp, current_timestamp),
      (239, 'Tavera Acosta', current_timestamp, current_timestamp),
      (240, 'Río Caribe', current_timestamp, current_timestamp),
      (240, 'Antonio José de Sucre', current_timestamp, current_timestamp),
      (240, 'El Morro de Puerto Santo', current_timestamp, current_timestamp),
      (240, 'Puerto Santo', current_timestamp, current_timestamp),
      (240, 'San Juan de las Galdonas', current_timestamp, current_timestamp),
      (241, 'El Pilar', current_timestamp, current_timestamp),
      (241, 'El Rincón', current_timestamp, current_timestamp),
      (241, 'General Francisco Antonio Váquez', current_timestamp, current_timestamp),
      (241, 'Guaraúnos', current_timestamp, current_timestamp),
      (241, 'Tunapuicito', current_timestamp, current_timestamp),
      (241, 'Unión', current_timestamp, current_timestamp),
      (242, 'Santa Catalina', current_timestamp, current_timestamp),
      (242, 'Santa Rosa', current_timestamp, current_timestamp),
      (242, 'Santa Teresa', current_timestamp, current_timestamp),
      (242, 'Bolívar', current_timestamp, current_timestamp),
      (242, 'Maracapana', current_timestamp, current_timestamp),
      (243, 'Bolívar', current_timestamp, current_timestamp),
      (244, 'El Paujil', current_timestamp, current_timestamp),
      (245, 'Cruz Salmerón Acosta', current_timestamp, current_timestamp),
      (245, 'Manicuare', current_timestamp, current_timestamp),
      (246, 'Tunapuy', current_timestamp, current_timestamp),
      (246, 'Campo Elías', current_timestamp, current_timestamp),
      (247, 'Irapa', current_timestamp, current_timestamp),
      (247, 'Campo Claro', current_timestamp, current_timestamp),
      (247, 'Maraval', current_timestamp, current_timestamp),
      (247, 'Soro', current_timestamp, current_timestamp),
      (248, 'Mejía', current_timestamp, current_timestamp),
      (249, 'Cumanacoa', current_timestamp, current_timestamp),
      (249, 'Aricagua', current_timestamp, current_timestamp),
      (249, 'San Fernando', current_timestamp, current_timestamp),
      (249, 'San Lorenzo', current_timestamp, current_timestamp),
      (250, 'Villa Frontado', current_timestamp, current_timestamp),
      (250, 'Catuaro', current_timestamp, current_timestamp),
      (250, 'Rendón', current_timestamp, current_timestamp),
      (250, 'San Cruz', current_timestamp, current_timestamp),
      (250, 'Santa María', current_timestamp, current_timestamp),
      (251, 'Altagracia', current_timestamp, current_timestamp),
      (251, 'Santa Inés', current_timestamp, current_timestamp),
      (251, 'Valentín Valiente', current_timestamp, current_timestamp),
      (251, 'Ayacucho', current_timestamp, current_timestamp),
      (251, 'San Juan', current_timestamp, current_timestamp),
      (251, 'Raúl Leoni', current_timestamp, current_timestamp),
      (251, 'Gran Mariscal', current_timestamp, current_timestamp),
      (252, 'Cristóbal Colón', current_timestamp, current_timestamp),
      (252, 'Bideau', current_timestamp, current_timestamp),
      (252, 'Punta de Piedras', current_timestamp, current_timestamp),
      (252, 'Güiria', current_timestamp, current_timestamp),
      (253, 'Andrés Bello', current_timestamp, current_timestamp),
      (254, 'Antonio Rómulo Costa', current_timestamp, current_timestamp),
      (255, 'Ayacucho', current_timestamp, current_timestamp),
      (255, 'San Pedro del Río', current_timestamp, current_timestamp),
      (256, 'Bolívar', current_timestamp, current_timestamp),
      (257, 'Cárdenas', current_timestamp, current_timestamp),
      (258, 'Córdoba', current_timestamp, current_timestamp),
      (259, 'Fernández Feo', current_timestamp, current_timestamp),
      (259, 'Alberto Adriani', current_timestamp, current_timestamp),
      (260, 'Francisco de Miranda', current_timestamp, current_timestamp),
      (261, 'García de Hevia', current_timestamp, current_timestamp),
      (261, 'Boca de Grita', current_timestamp, current_timestamp),
      (262, 'Guásimos', current_timestamp, current_timestamp),
      (263, 'Independencia', current_timestamp, current_timestamp),
      (262, 'Juan Germán Roscio', current_timestamp, current_timestamp),
      (264, 'Jáuregui', current_timestamp, current_timestamp),
      (265, 'José María Vargas', current_timestamp, current_timestamp),
      (266, 'Junín', current_timestamp, current_timestamp),
      (266, 'La Petrólea', current_timestamp, current_timestamp),
      (267, 'Libertad', current_timestamp, current_timestamp),
      (268, 'Capital Libertador', current_timestamp, current_timestamp),
      (269, 'Lobatera', current_timestamp, current_timestamp),
      (270, 'Michelena', current_timestamp, current_timestamp),
      (271, 'Panamericano', current_timestamp, current_timestamp),
      (272, 'Pedro María Ureña', current_timestamp, current_timestamp),
      (273, 'Delicias', current_timestamp, current_timestamp),
      (274, 'Samuel Darío Maldonado', current_timestamp, current_timestamp),
      (274, 'Boconó', current_timestamp, current_timestamp),
      (275, 'La Concordia', current_timestamp, current_timestamp),
      (275, 'San Juan Bautista', current_timestamp, current_timestamp),
      (275, 'Pedro María Morantes', current_timestamp, current_timestamp),
      (276, 'Seboruco', current_timestamp, current_timestamp),
      (277, 'Simón Rodríguez', current_timestamp, current_timestamp),
      (278, 'Sucre', current_timestamp, current_timestamp),
      (279, 'San José', current_timestamp, current_timestamp),
      (280, 'Uribante', current_timestamp, current_timestamp),
      (280, 'Juan Pablo Peñalosa', current_timestamp, current_timestamp),
      (280, 'Potosí', current_timestamp, current_timestamp),
      (281, 'San Judas Tadeo', current_timestamp, current_timestamp),
      (282, 'Araguaney', current_timestamp, current_timestamp),
      (282, 'El Jaguito', current_timestamp, current_timestamp),
      (283, 'Boconó', current_timestamp, current_timestamp),
      (284, 'Sabana Grande', current_timestamp, current_timestamp),
      (284, 'Cheregüé', current_timestamp, current_timestamp),
      (285, 'Arnoldo Gabaldón', current_timestamp, current_timestamp),
      (285, 'Bolivia', current_timestamp, current_timestamp),
      (285, 'Carrillo', current_timestamp, current_timestamp),
      (285, 'Manuel Salvador Ulloa', current_timestamp, current_timestamp),
      (286, 'Carache', current_timestamp, current_timestamp),
      (286, 'La Concepción', current_timestamp, current_timestamp),
      (286, 'Santa Cruz', current_timestamp, current_timestamp),
      (287, 'Escuque', current_timestamp, current_timestamp),
      (287, 'Santa Rita', current_timestamp, current_timestamp),
      (288, 'El Socorro', current_timestamp, current_timestamp),
      (288, 'Antonio José de Sucre', current_timestamp, current_timestamp),
      (289, 'Campo Elías', current_timestamp, current_timestamp),
      (289, 'Arnoldo Gabaldón', current_timestamp, current_timestamp),
      (290, 'Santa Apolonia', current_timestamp, current_timestamp),
      (290, 'La Ceiba', current_timestamp, current_timestamp),
      (291, 'Agua Santa', current_timestamp, current_timestamp),
      (291, 'Valerita', current_timestamp, current_timestamp),
      (292, 'Carmelo', current_timestamp, current_timestamp),
      (292, 'Santa María del Horcón', current_timestamp, current_timestamp),
      (293, 'Motatán', current_timestamp, current_timestamp),
      (293, 'Jalisco', current_timestamp, current_timestamp),
      (294, 'Pampán', current_timestamp, current_timestamp),
      (294, 'Santa Ana', current_timestamp, current_timestamp),
      (295, 'Pampanito', current_timestamp, current_timestamp),
      (295, 'Pampanito II', current_timestamp, current_timestamp),
      (296, 'Betijoque', current_timestamp, current_timestamp),
      (296, 'José Gregorio Hernández', current_timestamp, current_timestamp),
      (296, 'La Pueblita', current_timestamp, current_timestamp),
      (297, 'Carvajal', current_timestamp, current_timestamp),
      (297, 'Campo Alegre', current_timestamp, current_timestamp),
      (297, 'Antonio Nicolás Briceño', current_timestamp, current_timestamp),
      (298, 'Sabana de Mendoza', current_timestamp, current_timestamp),
      (298, 'Junín', current_timestamp, current_timestamp),
      (298, 'Valmore Rodríguez', current_timestamp, current_timestamp),
      (298, 'El Paraíso', current_timestamp, current_timestamp),
      (299, 'Andrés Linares', current_timestamp, current_timestamp),
      (299, 'Cristóbal Mendoza', current_timestamp, current_timestamp),
      (299, 'Carrillo', current_timestamp, current_timestamp),
      (300, 'Cabimbú', current_timestamp, current_timestamp),
      (300, 'Jajó', current_timestamp, current_timestamp),
      (300, 'La Mesa de Esnujaque', current_timestamp, current_timestamp),
      (300, 'Santiago', current_timestamp, current_timestamp),
      (300, 'La Quebrada', current_timestamp, current_timestamp),
      (301, 'Juan Ignacio Montilla', current_timestamp, current_timestamp),
      (301, 'La Beatriz', current_timestamp, current_timestamp),
      (301, 'La Puerta', current_timestamp, current_timestamp),
      (301, 'Mendoza del Valle de Momboy', current_timestamp, current_timestamp),
      (301, 'Mercedes Díaz', current_timestamp, current_timestamp),
      (301, 'San Luis', current_timestamp, current_timestamp),
      (302, 'El Guayabo', current_timestamp, current_timestamp),
      (302, 'Farriar', current_timestamp, current_timestamp),
      (303, 'Arístides Bastidas', current_timestamp, current_timestamp),
      (304, 'Bolívar', current_timestamp, current_timestamp),
      (305, 'Chivacoa', current_timestamp, current_timestamp),
      (305, 'Campo Elías', current_timestamp, current_timestamp),
      (306, 'Cocorote', current_timestamp, current_timestamp),
      (307, 'Independencia', current_timestamp, current_timestamp),
      (308, 'José Antonio Páez', current_timestamp, current_timestamp),
      (309, 'La Trinidad', current_timestamp, current_timestamp),
      (310, 'Manuel Monge', current_timestamp, current_timestamp),
      (311, 'Salóm', current_timestamp, current_timestamp),
      (311, 'Nirgua', current_timestamp, current_timestamp),
      (312, 'San Andrés', current_timestamp, current_timestamp),
      (312, 'Yaritagua', current_timestamp, current_timestamp),
      (313, 'San Felipe', current_timestamp, current_timestamp),
      (313, 'San Javier', current_timestamp, current_timestamp),
      (314, 'Sucre', current_timestamp, current_timestamp),
      (315, 'Urachiche', current_timestamp, current_timestamp),
      (316, 'Isla de Toas', current_timestamp, current_timestamp),
      (316, 'Monagas', current_timestamp, current_timestamp),
      (317, 'San Timoteo', current_timestamp, current_timestamp),
      (317, 'Libertador', current_timestamp, current_timestamp),
      (317, 'Pueblo Nuevo', current_timestamp, current_timestamp),
      (318, 'La Rosa', current_timestamp, current_timestamp),
      (318, 'Rómulo Betancourt', current_timestamp, current_timestamp),
      (318, 'San Benito', current_timestamp, current_timestamp),
      (318, 'Arístides Calvani', current_timestamp, current_timestamp),
      (319, 'Encontrados', current_timestamp, current_timestamp),
      (320, 'Moralito', current_timestamp, current_timestamp),
      (320, 'San Carlos del Zulia', current_timestamp, current_timestamp),
      (320, 'Santa Cruz del Zulia', current_timestamp, current_timestamp),
      (320, 'Santa Bárbara', current_timestamp, current_timestamp),
      (320, 'Urribarrí', current_timestamp, current_timestamp),
      (321, 'Carlos Quevedo', current_timestamp, current_timestamp),
      (321, 'Francisco Javier Pulgar', current_timestamp, current_timestamp),
      (322, 'La Concepción', current_timestamp, current_timestamp),
      (322, 'Mariano Parra León', current_timestamp, current_timestamp),
      (323, 'Concepción', current_timestamp, current_timestamp),
      (323, 'Chiquinquirá', current_timestamp, current_timestamp),
      (323, 'Potreritos', current_timestamp, current_timestamp),
      (324, 'Libertad', current_timestamp, current_timestamp),
      (324, 'Venezuela', current_timestamp, current_timestamp),
      (324, 'Campo Lara', current_timestamp, current_timestamp),
      (325, 'San José de Perijá', current_timestamp, current_timestamp),
      (326, 'mara', current_timestamp, current_timestamp),
      (327, 'Bolívar', current_timestamp, current_timestamp),
      (327, 'Coquivacoa', current_timestamp, current_timestamp),
      (327, 'Chiquinquirá', current_timestamp, current_timestamp),
      (327, 'Raúl Leoni', current_timestamp, current_timestamp),
      (327, 'Santa Lucía', current_timestamp, current_timestamp),
      (327, 'San Isidro', current_timestamp, current_timestamp),
      (328, 'Altagracia', current_timestamp, current_timestamp),
      (328, 'Faría', current_timestamp, current_timestamp),
      (328, 'San Antonio', current_timestamp, current_timestamp),
      (328, 'San José', current_timestamp, current_timestamp),
      (329, 'Guajira', current_timestamp, current_timestamp),
      (329, 'Elías Sánchez Rubio', current_timestamp, current_timestamp),
      (330, 'El Rosario', current_timestamp, current_timestamp),
      (331, 'San Francisco', current_timestamp, current_timestamp),
      (331, 'Los Cortijos', current_timestamp, current_timestamp),
      (332, 'Santa Rita', current_timestamp, current_timestamp),
      (332, 'Urribarrí', current_timestamp, current_timestamp),
      (333, 'Rafael', current_timestamp, current_timestamp),
      (333, 'Manuel Manrique', current_timestamp, current_timestamp),
      (334, 'Gibraltar', current_timestamp, current_timestamp),
      (334, 'Rómulo Gallegos', current_timestamp, current_timestamp),
      (335, 'Rafael Urdaneta ', current_timestamp, current_timestamp),
      (334, 'La Victoria', current_timestamp, current_timestamp),
      (335, 'Raúl Cuenca', current_timestamp, current_timestamp),
      (336, 'Jesús María Semprún', current_timestamp, current_timestamp);");
    $this->command->info('Las parroquias de venezuela fueron creadas por el elegido.');
  }

}
